name: Label PRs

on:
  pull_request:
    types: [opened, edited]
    branches: [main]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@36ad6b8842ea13d9ce2e4d22993bbf6fc0d20b5e # 0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
